name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Add working directory
      - name: Install dependencies
        working-directory: ./frontend  # Change to the frontend directory
        run: npm install

      - name: Run Prettier to check formatting
        working-directory: ./frontend  # Change to the frontend directory
        run: npm run prettier -- --check
        continue-on-error: false
